---
title: "Tarea 04"
author: "Josshua Cordero"
date: "14/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Carga librerías
```{r carga paquetes, message=FALSE, warning=FALSE}
library(sf)
library (raster)
library(leaflet)
library(leaflet.extras)
library(dplyr)
```
## Carga datos
```{r carega datos, message=FALSE, warning=FALSE}
# Carga de orquideas
orq <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
st_crs(orq) = 4326
#Carga de ASP
asp <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/sinac/asp/asp-wgs84.geojson",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
st_crs(asp) = 4326

# Carga de cantones
cantones <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
)
# Carga de provincias
provincias <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_provincias_simp_wgs84.geojson",
    quiet = TRUE
  )
```

## Cambiar tipos de datos y eliminar datos innecesarios
```{r eliminar datos}
#Cambiar datos a numéricos
orq <-
  orq %>%
  mutate(coordinateUncertaintyInMeters = as.numeric(coordinateUncertaintyInMeters)) %>%
  mutate (eventDate = as.Date(eventDate, "%Y-%m-%d"))

#Eliminar datos inncesarios
cat("Cantidad original de registros: ", nrow(orq))

orq <-
  orq %>%
  filter((coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters <= 1000)

cat("Cantidad de registros después de descartar los datos de alta incertidumbre en la ubicación >1000 : ", nrow(orq))

# Descartar registros especies NA
orq <-
  orq %>%
  na.omit(species)
cat("Cantidad de registros después de descartar los NA de especies: ", nrow(orq)) 
```


